/*
Codeforces - 1917B. Erase First or Second Letter
Time limit per test: 1 second
Memory limit per test: 256 megabytes

You are given a string s of length n. Let's define two operations you can apply on the string:
remove the first character of the string;
remove the second character of the string.

Your task is to find the number of distinct non-empty strings that can be generated by applying the given operations on the initial string any number of times (possibly zero), in any order.

Input
Each test consists of multiple test cases. The first line contains a single integer t (1 <= t <= 10^4) — the number of test cases. The description of the test cases follows.
The first line of each test case contains n (1 <= n <= 10^5) — the length of the string.
The second line of each test case contains the string s. It is guaranteed that the string only contains lowercase letters of the English alphabet.
It is guaranteed that the sum of n over all test cases does not exceed 2 * 10^5.

Output
For each test case, output a single integer: the number of distinct non-empty strings you can get.
*/



/* Approach - Prefix Distinct Character Tracking / Cumulative Substring Diversity Sum (Time: O(N), Space: O(N))
 * Basically, we completely annihilate O(N^2) substring enumeration by aggressively building a prefix frequency array, tracking the count of unique characters up to each index in pristine linear time!
 * * Observation: 
 * - The absolute core of this architecture is the Cumulative Distinct Prefix Invariant! Instead of generating all possible substrings or running a set over every slice, you track how many unique characters have appeared from index `0` up to `i` using a frequency vector and a running `count`. Summing up these prefix counts across the entire array elegantly calculates the total contribution of distinct characters.
 * - (Space Optimization Opportunity): While your `vector<int> distinct(n)` vector is crystal clear and easy to reason about, you don't actually need to store the entire prefix array in memory! As you compute each `distinct[i]` value on the fly during the loop, you can immediately add it to your running `sum`, reducing the auxiliary space complexity from O(N) down to absolute peak O(1)!
 * - (Fast I/O & Stream Handling): Maintaining standard competitive programming fast I/O hooks (`ios_base::sync_with_stdio(false); cin.tie(NULL);`) and ending output lines with `\n` instead of `endl` prevents unnecessary output buffer flushes, keeping execution blazing fast.
 * * How it runs:
 * First, we safely intercept array size `n` and target string `s`.
 * We initialize a frequency array for the 26 lowercase English letters and a running distinct character `count`.
 * We ignite a high-speed linear sweep across the string, updating frequencies and recording the number of unique characters seen up to index `i`.
 * We accumulate all prefix distinct counts into our `sum` variable.
 * Finally, we flush the total sum to the output stream with absolute mathematical precision at raw silicon speed!
 */


#include <bits/stdc++.h>
using namespace std;

void solve() {
    long long n;
    cin >> n; 

    string s;
    cin >> s;

    vector<int> distinct(n); // distinct[i] store distinct char seen before the indes i
    int count = 0; //count of distinct element;
    vector<int> freq(26);//store frequence of each char

    for(int i=0;i<n;i++){
        freq[s[i] - 'a']++;

        if(freq[s[i] -'a'] == 1){
            count++;
        }
        distinct[i] = count;
    }

    long long  sum = 0;
    for(int i : distinct){
        sum += i;
    }

    cout << sum << endl;
}

int main() {
    // Fast I/O
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    
    int t;
    cin >> t;
    while(t--) {
        solve();  
    }

    return 0;
}
