/*Leetcode ps - 3474. Lexicographically Smallest Generated String
You are given two strings, str1 and str2, of lengths n and m, respectively.
A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".*/

// approach -
// T- fill them with str2
// remaining spaces - mark them canchange = true
/* while validatinf F , if it violates {
           check from right to left :=
             if you can change a to b {
                if yes -> perfform
                else return ""
                }
} */



class Solution {
public:
    bool issame(string& word , string &str2 , int i , int m){
        for(int j = 0 ; j< m ;j++){
            if(word[i] != str2[j]) return false;
            i++;
        }
        return true;
    }
    string generateString(string str1, string str2) {
        int n = str1.length();
        int m = str2.length();
        int N = n+m-1;
        string word(N,'$'); // used $ as dummy character for now
        vector<bool> canchange(N, false);

        // fil up all T in str1
        for(int i=0;i<n;i++){
            if(str1[i]=='T'){
                int k =i;
                for(int j = 0 ;j<m ;j++ ){
                    if(word[k] != '$' && word[k] != str2[j]){
                        return ""; // if violation happen return ""
                    }
                    word[k] = str2[j]; // filling up from word[i] to word[i+j].
                    k++;
                }
            }
        }

        // fill remaning spaces for 'a' (greedy for lexicographical smallest )
        for(int i = 0 ;i < N;i++){
            if(word[i]=='$'){
                word[i]= 'a';
                canchange[i] = true;// we can change this a i case of violation of filling for 'F'
            }
        }

        // fill for F
        for(int i = 0 ;i<n;i++){
            if(str1[i] == 'F'){
                if(issame(word,str2,i,m)){//if same then we gotta make it unequal
                  bool changed = false;
                  for(int j = i+m-1 ; j>=i;j--){ // iterate from right
                    if(canchange[j] == true){
                        word[j] = 'b';
                        changed = true;
                        break;
                    }
                  }

                  if(!changed) return ""; // wasn't able to break equality so not possible to construct 
                }
            }
        }
         return word;
    }
};
